import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import { NavigationMenu } from "@/components/ui/navigation-menu";
import NavBar from "@/components/common/navbar";
import { adminRoutes } from "@/components/routes";
import { ThemeProvider } from "@/components/common/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <ThemeProvider
      attribute="class"
      defaultTheme='dark'
      enableSystem
      disableTransitionOnChange
      >
      
      {children}
      
      </ThemeProvider>
        </body>
    </html>
  );
}
